#!/bin/bash

#SBATCH -p general

#SBATCH --ntasks=1
#SBATCH --mem=500M
#SBATCH --time=0:30:00
#SBATCH --chdir=/N/project/Wuetal_baboon/callability/

module unload gcc
module unload python
module load gcc/9.3.0
module load python/3.9.8
module load bcftools

module load bcftools
echo $GQ
for i in {1..19}
do
bcftools view -i'FORMAT/GQ[2] > '$GQ hets/hetxmitDP.trio$i.vcf.gz | grep -v '#' | wc -l >> hets/columns/het_dpgq$GQ.column
wc -l < hets/hetpiled_positionsGQ$GQ.trio$i.txt >> hets/columns/het_bamgq$GQ.column
bcftools query -R hets/hetpiled_positionsGQ$GQ.trio$i.txt -f'[%AD\t]\n' hets/hetxmitDP.trio$i.vcf.gz | cut -f3 | sed 's/,/\t/g' | tee \
>(awk '$2/($1 + $2) > 0.30' | wc -l >> hets/columns/het_ab30gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.35' | wc -l >> hets/columns/het_ab35gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.40' | wc -l >> hets/columns/het_ab40gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.45' | wc -l >> hets/columns/het_ab45gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.50' | wc -l >> hets/columns/het_ab50gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.55' | wc -l >> hets/columns/het_ab55gq$GQ.column) \
>(awk '$2/($1 + $2) > 0.60' | wc -l >> hets/columns/het_ab60gq$GQ.column) >/dev/null
done
